export default {
	'zh-CN': {
		hysy: '欢迎使用',
		login: {
			title_0: '您好,',
			title_1: '欢迎来到JakobLife',
			input_0: '请输入会员名或绑定的手机号',
			input_1: '请输入密码',
			input_2: '请输入验证码',
			text_0: '忘记密码',
			text_1: '短信登陆',
			text_2: '密码登录',
			text_3: '获取验证码',
			text_4: '同意',
			text_5: '《JakobLife软件服务使用协议》',
			text_6: '登录',
			text_7: '还没有JakobLife账号？',
			text_8: '新用户去注册',
			text_9: '其它登陆方式',
			text_10: '请填写图形验证码',
			text_11: '请输入图形验证码',
			text_12: '看不清？换一张',
			text_13: '确定',
			text_14: '取消',
			text_15: '验证码错误',
			text_16: '请输入会员或绑定的手机号',
			text_17: '请同意服务协议',
			text_18: '请输入验证码',
			text_19: '请输入验证码结果'
		},
		zhuce: '注册',
		zhuceitem: {
			input_0: '请输入会员名',
			input_1: '请确认密码',
			toast_0: '会员名未设置',
			toast_1: '密码未设置',
			toast_2: '再次输入的密码未设置',
			toast_3: '两次输入的密码不一致',
			toast_4: '请阅读并同意《JakobLife软件服务使用协议》',
			check_text: '已阅读并同意',
			btn_0: '下一步',
			title_0: '绑定手机号',
			input_2: '请输入手机号',
			input_3: 's后可重发',
			input_4: '重新获取',
			toast_5: '不能重复获取',
			btn_1: '完成',
			title_1: '恭喜您，注册成功!',
			title_2: '建议您完善以下信息，以下信息将用于基础分析。',
			title_3: '性别',
			title_4: '出生日期',
			title_5: '身高',
			title_6: '体重',
			btn_2: '跳过',
			title_7: '请选择',
			title_8: '请输入',
			select_0: '男',
			select_1: '女',
			toast_6: '请选择性别',
			toast_7: '请选择出生日期',
			toast_8: '请输入身高',
			toast_9: '请输入体重',
		},
		XZGLLX: '选择管理类型',
		XZGLLXitem: {
			title_0: '请选择一项您主要想管理的内容',
			title_1: '之后您可以随时切换主要管理项目',
			button_0: '血压管理',
			button_1: '体脂管理',
			button_2: '暂不选择',
			title_2: '绑定设备后测量数据将自动上传。',
			title_3: '在绑定设备前，请您充分阅读、理解',
			title_4: '并同意以下协议政策。',
			title_5: '《JakobLife软件移动客户端用户使用规范》',
			title_6: '《JakobLife隐私政策》',
			title_7: '《敏感个人信息处理情况的说明》',
			title_8: '《向第三方提供个人信息情况的说明》',
			button_3: '拒绝',
			title_9: '请选择血压计型号',
			title_10: '请选择体脂秤型号',
			button_4: '暂不绑定'
		},
		BDSB: '绑定设备',
		BDSBitem: {
			title_0: "1、将SIM卡按照标识正确插入设备中；",
			title_1: "2、使用“JakobLife”APP扫描机身标贴的IMEI码或包装彩盒标贴的二维码进行绑定。",
			title_2: '准备就绪',
			title_3: '绑定失败？',
			title_4: '1、请确保按照标识正确插入SIM卡在设备中，并检查网络连接是否正常，若无信号请在关机状态下重新插入SIM卡；',
			title_5: '2、请扫描机身标贴的IMEI码或包装彩盒标贴的二维码重新绑定；',
			title_6: '3、重启设备进行尝试；',
			title_7: '4、若仍无法绑定，请拨打我们的服务热线0755-86561393。',
			title_8: '知道了',
			title_9: '请将条码放入扫码框内，即可自动扫描',
			button_0: '确定绑定',
			title_11: '设备绑定成功！',
			title_12: '请扫描设备的设备码'
		},
		SYXY_title: '使用协议',
		SYXYitem: {
			button: '我已阅读并同意',
			pos_0: '我确认已满14周岁',
			pos_1: '勾选表示已阅读并同意',
			pos_2: '《JakobLife软件移动客户端用户使用规范》',
			pos_3: '《JakobLife隐私政策》',
			pos_4: '《敏感个人信息处理情况的说明》',
			pos_5: '《向第三方提供个人信息情况的说明》',

		},
		WJMM: '重置密码',
		WJMMitem: {
			input_0: '请输入会员名或手机号',
			title_0: '密码已重置成功，请重新登录!'

		},
		shouye: '首页',
		shouye_item: {
			title_0: '注：本页面显示均为最近测量数据',
			title_1: '血压',
			title_2: '调整卡片顺序',
			title_3: '步数',
			title_4: '计步',
			title_5: '最新体重',
			title_6: '初始体重',
			title_7: '目标体重',
			title_8: '热量',
			title_9: '卡路里',
			title_10: '体围数据',
			title_11: '单位：CM',
			title_12: '胸围',
			title_13: '腰围',
			title_14: '臀围',
			title_15: '上臀围',
			title_16: '大腿围',
			title_17: '小腿围',
			title_18: '确保每天摄入足够的水，避免因口渴误以为饥饿。',
			title_19: '记体重',
			title_20: '记体围',
			title_21: '今天',
			title_22: '手动输入',
			title_23: '滑动输入',
			title_24: '请输入胸围',
			title_25: '请输入腰围',
			title_26: '请输入臀围',
			title_27: '请输入上臀围',
			title_28: '请输入大腿围',
			title_29: '请输入小腿围',
			title_30: '年',
			title_31: '月',
			title_32: '日',
			title_33: '时',
			title_34: '分',
			title_35: '周',
			title_36: '个月'



		},

		qushi: '趋势',

		qushiitem: {
			title_0: '最近血压',
			title_1: '平均血压',
			title_2: '最高血压',
			title_3: '最低血压',
			title_4: '请输入收缩压',
			title_5: '请输入舒张压',
			title_6: '请输入脉搏',
			title_7: '正常血压',
			title_8: '一级高血压',
			title_9: '二级高血压',
			title_10: '最近7天平均体重/kg',
			title_11: '变化速度kg/周',
			title_12: '今日体重',
			title_13: '最高体重/kg',
			title_14: '最低体重/kg',
			title_15: '平均体重/kg',
			title_16: '暂无数据',
			title_17: '历史记录',
			title_18: '删除记录',
			title_19: '提示',
			title_20: '是否删除',


		},

		gongxiang: '共享',

		gongxiangitem: {
			title_0: '与他人共享',
			title_1: '他人与我共享',
			title_2: '暂无用户与您共享健康数据。',
			title_3: '健康共享',
			title_4: '掌握权在您手中',
			title_5: '安全共享您的健康数据，使亲友及时了解您的健康状况。',
			title_6: '图标汇总和通知',
			title_7: '您共享的数据将在其“JakobLife”App中显示。\n有更新时还可以向共享对象发送通知',
			title_8: '私密且安全',
			title_9: '仅分享每个主题的摘要，而非详细信息。信息会加密，您可以随时停止共享。',
			title_10: '共享对象，需同样下载“JakobLife”App,并持有账号，否则无法共享。',
			title_11: '共享给',
			title_12: '请搜索会员名或手机号',
			title_13: '您已向',
			title_14: '发出共享健康数据邀请',
			title_15: '暂无用户与您共享健康数据。',
			title_16: '您正在与',
			title_17: '共享以下健康数据。',
			title_18: '正在与您共享以下健康数据。',
			title_19: '注：本页面显示均为最近测量数据',
			title_20: '请选择要共享的数据',
			title_21: '您将与',
			title_22: ',您始终可以更改共享或停止共享，若停止共享，您的数据将从其设备上移除。',
			title_23: '舒张压',
			title_24: '收缩压',
			title_25: '脉率',
			title_26: '编辑与共享',
			title_27: '全选',
			title_28: '取消共享',
			title_29: '确认',
			title_30: '共享列表',
			title_31: '编辑',
			title_32: '您取消了共享操作',


		},

		wode: '我的',
		wodelist: {
			xiaoxi: '消息',
			xiaoxiitem: {
				button_0: '清空',
				title_0: '暂无消息',
				title_1: '邀请',
				title_2: '想和您共享健康数据',
				button_1: '接受',
				title_3: '已与您共享共享健康数据'

			},

			name: '未登录',
			wdjkda: '我的健康档案',
			wdjkdaitem: {
				title_0: '头像',
				title_1: '会员名',
				title_2: '身体基础信息',
				title_3: '健康档案',


			},
			dwss: '单位设置',
			sbgl: '设备管理',
			sbglitem: {
				title_0: '添加设备',
				title_1: '选择该设备',
				title_2: '删除该设备',
			},
			txsz: '提醒设置',
			txszitem: {
				tx_title0: '请输入标签',
				tx_title1: '标签',
				title_0: '吃药',
				title_1: '测试',
				title_2: '时间',
				title_3: '重复',
				title_4: '铃声',
				title_5: '震动',
				title_6: '稍后提醒',
				title_7: '周一',
				title_8: '周二',
				title_9: '周三',
				title_10: '周四',
				title_11: '周五',
				title_12: '周六',
				title_13: '周天',
				title_14: '选取歌曲',
				title_15: '雷达(默认)',
				title_16: '波浪',
				title_17: '倒影',
				title_18: '灯塔',
				title_19: '山顶',
				title_20: '水晶',
				title_21: '无',

			},
			bzzx: '帮助中心',
			bzzxitem: {
				title_0: '血压计绑定问题',
				title_1: '体脂秤绑定问题',
				title_2: '数据同步',
				title_3: '4G款血压计绑定教程',
				title_4: '4G款血压计绑定不了',
				title_5: 'WIFI款血压计绑定教程',
				title_6: 'WIFI款血压计绑定不了',
				title_7: '已解决',
				title_8: '继续反馈',
				title_9: '4G款体脂秤绑定教程',
				title_10: '4G款体脂秤绑定不了',
				title_11: 'WIFI款体脂秤绑定教程',
				title_12: 'WIFI款体脂秤绑定不了',
				title_13: '数据同步失败',
				title_14: '数据同步等待时间长',
				title_15: '',
				title_16: '',

			},
			aqzx: '安全中心',
			aqzxitem: {
				title_0: '未设置会员名',
				title_1: '设置登录密码',
				title_2: '第三方账号绑定',
				title_3: '微信',
				title_4: '原手机号验证',
				title_5: '请输入您原来的绑定的手机号',
				title_6: '请输入您新绑定的手机号',
				title_7: '新手机号验证',
				title_8: '原手机号不可用？',
				title_9: '使用其他方法验证。',
				title_10: '新号码已绑定成功！',
				title_11: '新手机号绑定',
				title_12: '退出登录',
				title_13: '未绑定',
				title_14: '会员名修改',
				title_15: '请输入新的会员名',

			},
			gygx: '关于&更新',
			gygxitem: {
				title_0: '当前版本:',
				title_1: '备案号:苏ICP备2024092533号-1',
				title_2: '给JakobLife好评',
				title_3: 'JakobLife软件移动客户端用户使用规范',
				title_4: 'JakobLife隐私政策',
				title_5: '敏感个人信息处理情况说明',
				title_6: '向第三方提供个人信息情况的说明',
				title_7: '已收集个人信息清单',
				title_8: '第三方共享个人清单',
				title_9: '医疗器械使用安全提示',
			},


			zx_title0: '注销账号',
			zx_titles0: '您即将注销',
			zx_titles1: '您账号下的JakobLife账号！',
			zx_titles2: '安全验证',
			zx_titles3: '您的JakobLife账号服务权益处于安全状态。',
			zx_titles4: '提前保留重要信息',
			zx_titles5: '由您本人发起，且注销前，您应自行处理相关数据及信息，如NFC或eSIM卡等虚拟服务中的个人数据。',
			zx_titles6: '请您谨慎操作',
			zx_titles7: '账号注销后，所有数据将被彻底删除且无法恢复',
			zx_titles8: '账号注销服务，不会影响您后续对JakobLife产品或服务的使用。',
			zx_title1: '注销JakobLife账号',
			zx_title2: '您将放弃以下资产或权益！',
			zx_title3: '该账号所有的数据将被清空',
			zx_title4: '所有设备会与您当前登录的账号解除绑定，并清除设备之前存储在服务端的数据。',
			zx_title5: '在手机中，账户的缓存数据将被清除',
			zx_title6: '同时，还将撤销您对用户协议和隐私政策的同意，并退出JakobLife应用。',
			zx_title7: '本人已阅读并同意注销协议',
			zx_title8: '再想想',
			zx_title9: '确认注销',
		}


	},
	'en-US': {
		hysy: 'Welcome to use',
		login: {
			title_0: 'Hello,',
			title_1: 'Welcome to JakobLife',
			input_0: 'Please enter the member name or bound mobile phone number',
			input_1: 'Please enter password',
			input_2: 'Please enter the verification code',
			text_0: 'Forgot password',
			text_1: 'SMS login',
			text_2: 'Password login',
			text_3: 'Get verification code',
			text_4: 'agree',
			text_5: '《JakobLife Software Service Usage Agreement》',
			text_6: 'Log in',
			text_7: "Don't have an JakobLife account yet?",
			text_8: 'The new user registers',
			text_9: 'Other login methods',
			text_10: 'Please fill in the graphic verification code',
			text_11: 'Please enter the graphic verification code',
			text_12: "Can't see? Change one",
			text_13: 'OK',
			text_14: 'Cancel',
			text_15: 'Verification code error',
			text_16: 'Please enter the member or bound mobile phone number',
			text_17: 'Please agree to the service agreement',
			text_18: 'Please enter the verification code',
			text_19: 'Please enter the verification code result'

		},
		zhuce: 'Sign in',
		zhuceitem: {
			input_0: 'Please enter your member name',
			input_1: 'Please confirm the password',
			toast_0: 'The member name is not set',
			toast_1: 'Password not set',
			toast_2: 'The reentered password is not set',
			toast_3: 'The two passwords are different',
			toast_4: 'Please read and agree to the《JakobLife Software Service Usage Agreement》',
			check_text: 'Read and agree',
			btn_0: 'next',
			title_0: 'Bind mobile phone number',
			input_2: 'Please enter your phone number',
			input_3: 's You can resend it later',
			input_4: 'reacquire',
			toast_5: 'non-repeatable',
			btn_1: 'complete',
			title_1: 'Congratulations, registration success!',
			title_2: 'It is recommended that you complete the following information, which will be used for basic analysis.',
			title_3: 'sex',
			title_4: 'Date of birth',
			title_5: 'height',
			title_6: 'weight',
			btn_2: 'skip',
			title_7: 'Please select',
			title_8: 'Please enter',
			select_0: 'male',
			select_1: 'female',
			toast_6: 'Please select gender',
			toast_7: 'Please select a date of birth',
			toast_8: 'Please enter height',
			toast_9: 'Please enter your weight',
		},
		XZGLLX: 'Select management type',
		XZGLLXitem: {
			title_0: 'Please select one item that you want to manage primarily',
			title_1: 'Then you can switch major management items at any time',
			button_0: 'Blood pressure management',
			button_1: 'Body fat management',
			button_2: 'Hold off',
			title_2: 'The measurement data is automatically uploaded after the device is bound.',
			title_3: 'Read and understand before binding the device',
			title_4: 'And agree to the following agreement policy.',
			title_5: '《Jakoblife software mobile client user usage specification》',
			title_6: '《JakobLife Privacy Policy》',
			title_7: '《A description of the handling of sensitive personal information》',
			title_8: '《A description of the provision of personal information to third parties》',
			button_3: 'Turn down',
			title_9: 'Please select a sphygmomanometer model',
			title_10: 'Please select a body fat scale model',
			button_4: 'unbind'
		},

		BDSB: 'Bind device',
		BDSBitem: {
			title_0: "1. Insert the SIM card into the device correctly according to the label;",
			title_1: "2. Use 'JakobLife' APP to scan the IMEI code of the body label or the two-dimensional code of the packaging color box label for binding.",
			title_2: 'Be ready',
			title_3: 'Failed to bind?',
			title_4: '1. Please ensure that the SIM card is correctly inserted into the device according to the sign, and check whether the network connection is normal. If there is no signal, please reinsert the SIM card in the shutdown state;',
			title_5: '2, please scan the IMEI code of the body label or the two-dimensional code of the packaging box label to re-bind;',
			title_6: '3. Restart the device to try;',
			title_7: '4, if still unable to bind, please call our service hotline 0755-86561393.',
			title_8: 'I got it',
			title_9: 'Please put the bar code into the scanning box to scan automatically',
			button_0: 'Deterministic binding',
			title_10: 'In the bound device, please do not exit the app',
			title_11: 'Device binding successful!',
			title_12: 'Scan the device code'


		},

		SYXY_title: 'Usage agreement',
		SYXYitem: {
			button: 'I have read and agree',
			pos_0: 'I confirm that I am over 14 years old',
			pos_1: 'If checked, you have read and agree',
			pos_2: '《JakobLife software mobile client user usage specification》',
			pos_3: '《JakobLife Privacy Policy》',
			pos_4: '《A description of the handling of sensitive personal information》',
			pos_5: '《A description of the provision of personal information to third parties》',
		},
		WJMM: 'Reset password',
		WJMMitem: {
			input_0: 'Please enter your member name or mobile number',
			title_0: 'Password has been reset successfully, please login again!'

		},
		shouye: 'Home page',
		shouye_item: {
			title_0: 'Note: This page shows the most recent measurement data',
			title_1: 'Blood pressure',
			title_2: 'Reorder cards',
			title_3: 'Step number',
			title_4: 'Step count',
			title_5: 'Latest weight',
			title_6: 'Initial weight',
			title_7: 'Target weight',
			title_8: 'heat',
			title_9: 'calorie',
			title_10: 'Body circumference data',
			title_11: 'unit：CM',
			title_12: 'Chest circumference',
			title_13: 'waistline',
			title_14: 'Hip circumference',
			title_15: 'Upper hip circumference',
			title_16: 'Thigh circumference',
			title_17: 'Calf circumference',
			title_18: 'Make sure to drink enough water each day to avoid mistaking thirst for hunger.',
			title_19: "Keep track of one's weight",
			title_20: 'Body circumference',
			title_21: 'today',
			title_22: 'Manual input',
			title_23: 'Sliding input',
			title_24: 'Please enter your chest size',
			title_25: 'Please enter waist circumference',
			title_26: 'Please enter hip measurement',
			title_27: 'Please enter upper hip circumference',
			title_28: 'Please enter thigh circumference',
			title_29: 'Please enter calf circumference',
			title_30: 'years',
			title_31: 'month',
			title_32: 'day',
			title_33: 'hours',
			title_34: 'minutes',
			title_35: 'weeks',
			title_36: 'months'
		},
		qushi: 'Tendency',
		qushiitem: {
			title_0: 'Recent blood pressure',
			title_1: 'Mean blood pressure',
			title_2: 'Maximum blood pressure',
			title_3: 'Minimum blood pressure',
			title_4: 'Please enter systolic pressure',
			title_5: 'Please enter diastolic pressure',
			title_6: 'Please enter pulse',
			title_7: 'Normal blood pressure',
			title_8: 'Primary hypertension',
			title_9: 'Secondary hypertension',
			title_10: 'Average weight /kg in the last 7 days',
			title_11: "Change rate kg/ week",
			title_12: "Today's weight",
			title_13: 'Maximum weight /kg',
			title_14: 'Minimum weight /kg',
			title_15: 'Average weight /kg',
			title_16: 'No data available',
			title_17: 'Historical record',
			title_18: 'Delete record',
			title_19: 'Tips',
			title_20: 'Delete or not',
		},
		gongxiang: 'Share',
		gongxiangitem: {
			title_0: 'Share with others',
			title_1: 'Others share with me',
			title_2: 'No user is sharing health data with you.',
			title_3: 'Healthy sharing',
			title_4: 'The power is in your hands',
			title_5: 'Share your health data securely to keep friends and family informed of your health status.',
			title_6: 'Icon summary and notification',
			title_7: 'The data you share will be displayed in their "JakobLife" App.\nYou can also send notifications to shared objects when there are updates',
			title_8: 'Private and secure',
			title_9: 'Only summaries of each topic are shared, not details. The information is encrypted and you can stop sharing it at any time.',
			title_10: 'To share objects, you need to also download the "JakobLife" App and hold an account, otherwise it cannot be shared.',
			title_11: 'Share with',
			title_12: 'Please search for member name or mobile number',
			title_13: 'You have sent an invitation to',
			title_14: 'to share health data',
			title_15: 'No user is sharing health data with you.',
			title_16: 'You are sharing the following health data with ',
			title_17: '',
			title_18: 'is sharing the following health data with you',
			title_19: 'Note: This page shows the most recent measurement data',
			title_20: 'Please select the data you want to share',
			title_21: 'You will share the following health data with',
			title_22: '，you can always change the sharing or stop the sharing, if you stop the sharing, your data will be removed from their device.',
			title_23: 'Diastolic blood pressure',
			title_24: 'Systolic blood pressure',
			title_25: 'Pulse rate',
			title_26: 'Edit and share',
			title_27: 'select all',
			title_28: 'unshare',
			title_29: 'verify',
			title_30: 'Shared list',
			title_31: 'EDITOR',
			title_32: 'You cancelled the sharing operation',
		},
		wode: 'mine',
		wodelist: {
			xiaoxi: 'message',
			xiaoxiitem: {
				button_0: 'Clear',
				title_0: 'No record',
				title_1: 'Invite',
				title_2: 'want to share health data with you',
				button_1: 'Accept',
				title_3: 'Shared health data is shared with you'
			},
			name: 'Not logged in',
			wdjkda: 'My health records',
			wdjkdaitem: {
				title_0: 'avatar',
				title_1: 'Member name',
				title_2: 'Body basic information',
				title_3: 'Health record',


			},
			dwss: 'Unit setting',
			sbgl: 'Equipment management',
			sbglitem: {
				title_0: 'Add device',
				title_1: 'Select the device',
				title_2: 'Delete the device',
			},
			txsz: 'Reminder setting',
			txszitem: {
				tx_title0: 'Please enter label',
				tx_title1: 'tag',
				title_0: 'Take medicine',
				title_1: 'Test',
				title_2: 'Time',
				title_3: 'Repeat ',
				title_4: 'Ringtone ',
				title_5: 'Vibration ',
				title_6: 'Remind later',
				title_7: 'Monday',
				title_8: 'Tuesday',
				title_9: 'Wednesday',
				title_10: 'Thursday',
				title_11: 'Friday',
				title_12: 'Saturday',
				title_13: 'Sunday',
				title_14: 'Select song',
				title_15: 'Radar (default)',
				title_16: 'Wave',
				title_17: 'Reflection',
				title_18: 'Lighthouse',
				title_19: 'The top of the mountain',
				title_20: 'Crystal',
				title_21: 'None',
			},
			bzzx: 'Help center',
			bzzxitem: {
				title_0: 'Sphygmomanometer binding problem',
				title_1: 'Body fat scale binding problem',
				title_2: 'Data synchronization',
				title_3: '4G blood pressure monitor binding tutorial',
				title_4: "4G blood pressure monitors don't work",
				title_5: 'WIFI sphygmomanometer binding tutorial',
				title_6: "WIFI sphygmomanometer doesn't work",
				title_7: 'resolved',
				title_8: 'Continued feedback',
				title_9: '4G body fat scale binding tutorial',
				title_10: "4G body fat scales don't bind",
				title_11: 'WIFI body fat scale binding tutorial',
				title_12: "WIFI body fat scales don't bind",
				title_13: 'Data synchronization failure',
				title_14: 'Data synchronization takes a long time',
				title_15: '',
				title_16: '',

			},
			aqzx: 'Safety center',
			aqzxitem: {
				title_0: 'No member name is set',
				title_1: 'Set login password',
				title_2: 'Third-party account binding',
				title_3: 'wechat',
				title_4: 'Original phone number verification',
				title_5: 'Please enter your original bound phone number',
				title_6: 'Please enter your newly bound phone number',
				title_7: 'New phone number verification',
				title_8: 'Your original phone number is not available?',
				title_9: 'Verify using other methods.',
				title_10: 'The new number is bound successfully！',
				title_11: 'New phone number binding',
				title_12: 'Log out',
				title_13: 'Not yet bound',
				title_14: 'Member name modification',
				title_15: 'Please enter a new member name',

			},
			gygx: 'About & Update',
			gygxitem: {
				title_0: 'Current version:',
				title_1: 'Record number: Su ICP No. 2024092533 -1',
				title_2: 'Praise for JakobLife',
				title_3: 'JakobLife software mobile client user usage specification',
				title_4: 'JakobLife Privacy Policy',
				title_5: 'Instructions for sensitive personal information',
				title_6: 'A description of the provision of personal information to third parties',
				title_7: 'List of personal information collected',
				title_8: 'Third parties share personal lists',
				title_9: 'Safety tips for medical device use',
			},
			zx_title0: 'Cancel account',
			zx_titles0: 'You are about to log out',
			zx_titles1: 'JakobLife account under your account!',
			zx_titles2: 'Security verification',
			zx_titles3: 'Your JakobLife account service rights are secure.',
			zx_titles4: 'Keep important information in advance',
			zx_titles5: 'Initiated by you, and before logout, you should handle the relevant data and information, such as personal data in virtual services such as NFC or eSIM card.',
			zx_titles6: 'Exercise caution when performing this operation',
			zx_titles7: 'After the account is deleted, all data will be completely deleted and cannot be recovered',
			zx_titles8: 'The account cancellation service will not affect your subsequent use of JakobLife products or services.',
			zx_title1: 'Log out of JakobLife',
			zx_title2: 'You will give up the following assets or interests!',
			zx_title3: 'All data of the account will be deleted',
			zx_title4: 'All devices will be unbound from the account you are currently logged in to and the data previously stored on the server will be cleared.',
			zx_title5: 'In the phone, the cached data of the account will be cleared',
			zx_title6: 'You will also withdraw your consent to the User Agreement and Privacy Policy and withdraw from the JakobLife app.',
			zx_title7: 'I have read and agree to cancel the agreement',
			zx_title8: 'Think again',
			zx_title9: 'Confirm cancellation',

		}

	}
}